server:
  port: 8848
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
      prefer-ip-address: true
spring:
  application:
    name: AIGOU_CONFIGS
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dzc265520/aigou_config.git
          username: dzc265520
          password: dzc19971013